package io.openems.edge.controller.tess.timeofusetariff;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Tess Time-Of-Use Tariff", //
		description = "Charges the thermal energy storage up to its hardware maximum temperature in cheap "
				+ "electricity price quarters, so the Heating device does not need to run in expensive hours.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlTessTimeOfUseTariff0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Tess-ID", description = "ID of the ManagedThermalEss; a single storage or a Tess.Cluster.")
	String tess_id() default "tess0";

	@AttributeDefinition(name = "Thermal Efficiency", description = "Thermal output per electrical input used in the "
			+ "optimization, e.g. heat pump COP (3.0), heating element (1.0).")
	double efficiency() default 1.0;

	@AttributeDefinition(name = "Thermal Demand", description = "Fallback average thermal discharge power [W] when no "
			+ "prediction for the storage's ThermalDischargePower channel is available.")
	int thermalDemand() default 0;

	@AttributeDefinition(name = "Tess target filter", description = "This is auto-generated by 'Tess-ID'.")
	String tess_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Tess Time-Of-Use Tariff [{id}]";
}
