package io.openems.edge.simulator.tess.reacting;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Simulator ThermalEss Reacting", //
		description = "This simulates a 'reacting' Thermal Energy Storage System.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "tess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Volume [L]", description = "Water volume in liters")
	int volume() default 300;

	@AttributeDefinition(name = "Initial State of Charge [%]")
	int initialSoc() default 50;

	@AttributeDefinition(name = "Max Temperature [°C]", description = "Physical maximum temperature (100% SoC / hardware limit) in °C")
	float maxTemperature() default 80;

	@AttributeDefinition(name = "Min Temperature [°C]", description = "Physical minimum temperature (0% SoC reference) in °C")
	float minTemperature() default 20;

	@AttributeDefinition(name = "Max Target Temperature [°C]", description = "Operating band upper limit; heating switches off at or above this temperature in °C")
	float maxTargetTemperature() default 70;

	@AttributeDefinition(name = "Min Target Temperature [°C]", description = "Operating band lower limit; heating switches on at or below this temperature in °C")
	float minTargetTemperature() default 50;

	@AttributeDefinition(name = "Heating-IDs", description = "IDs of Heating components feeding this storage.")
	String[] heating_ids() default {};

	@AttributeDefinition(name = "Heating target filter", description = "This is auto-generated by 'Heating-IDs'.")
	String Heating_target() default "(enabled=true)";

	@AttributeDefinition(name = "Datasource-ID", description = "ID of Simulator Datasource providing the 'ThermalConsumption' channel [W].")
	String datasource_id() default "datasource0";

	@AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
	String datasource_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Simulator ThermalEss Reacting [{id}]";
}
