package io.openems.edge.controller.tess.delaycharge;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Tess Delay-Charge", //
		description = "Spreads the charging of the thermal energy storage over the remaining PV production "
				+ "time, so it becomes full right when production ends.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlTessDelayCharge0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Tess-ID", description = "ID of the ManagedThermalEss; a single storage or a Tess.Cluster.")
	String tess_id() default "tess0";

	@AttributeDefinition(name = "Mode", description = "AUTOMATIC derives the target time from the predicted end of "
			+ "PV production; MANUAL uses the configured target time.")
	Mode mode() default Mode.AUTOMATIC;

	@AttributeDefinition(name = "Manual Target Time", description = "Time of day until which the storage should be "
			+ "fully charged, e.g. '17:00'. Used in MANUAL mode and as fallback.")
	String manualTargetTime() default "17:00";

	@AttributeDefinition(name = "Tess target filter", description = "This is auto-generated by 'Tess-ID'.")
	String tess_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Tess Delay-Charge [{id}]";
}
