package io.openems.edge.meter.phoenixcontact;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Meter Phoenix Contact", //
		description = "Implements the Phoenix Contact EEM-XM series meter (EEM-XM157/355/357/375/377).")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Meter-Type", description = "Grid, Production (=default) or Consumption Meter?")
	MeterType type() default MeterType.PRODUCTION;

	@AttributeDefinition(name = "Phase Wiring", description = "The wiring of the meter (3P4W, 3P3W or 1P2W)")
	PhaseWiring phaseWiring() default PhaseWiring.THREE_PHASE_FOUR_WIRE;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	@AttributeDefinition(name = "Invert measurement", description = "Inverts power and current, swaps production/consumption and lagging/leading energy")
	boolean invert() default false;

	String webconsole_configurationFactory_nameHint() default "Meter Phoenix Contact [{id}]";

}