package io.openems.edge.heat.tess.layer;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.heat.tess.core.Connection;

@ObjectClassDefinition(//
		name = "Thermal ESS Layer", //
		description = "A thermal energy storage layer whose state is estimated from a temperature sensor and the "
				+ "supply and return temperatures of a circulating heat pump.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "tess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Volume [L]", description = "Water volume of the layer in liters.")
	int volume() default 300;

	@AttributeDefinition(name = "Max Temperature [°C]", description = "Physical maximum temperature (100% SoC / hardware limit) in °C.")
	float maxTemperature() default 80;

	@AttributeDefinition(name = "Target Temperature [°C]", description = "Target of autonomous operation; heating switches off at or above this temperature in °C. Explicit charge targets may exceed it up to Max Temperature.")
	float targetTemperature() default 70;

	@AttributeDefinition(name = "Min Temperature [°C]", description = "Hard lower limit (0% SoC); heating switches on at or below this temperature in °C.")
	float minTemperature() default 20;

	@AttributeDefinition(name = "Sensor Channel", description = "Channel-Address of the temperature sensor in deci-°C, e.g. 'thermometer0/Temperature'.")
	String sensorChannelAddress() default "thermometer0/Temperature";

	@AttributeDefinition(name = "Sensor Height [%]", description = "Height of the sensor's immersion sleeve relative to the layer; 0% is the bottom, 100% the top.")
	float sensorHeight() default 50;

	@AttributeDefinition(name = "Connection", description = "How the heat pump is connected: its water flows directly through the layer, or through a heat exchanger coil.")
	Connection connection() default Connection.DIRECT;

	@AttributeDefinition(name = "Supply Height [%]", description = "Height of the heat pump's supply connection relative to the layer; 0% is the bottom, 100% the top.")
	float supplyHeight() default 90;

	@AttributeDefinition(name = "Return Height [%]", description = "Height of the heat pump's return connection relative to the layer; 0% is the bottom, 100% the top.")
	float returnHeight() default 10;

	@AttributeDefinition(name = "Heating-IDs", description = "IDs of Heating components feeding this layer.")
	String[] heating_ids() default {};

	@AttributeDefinition(name = "Heating target filter", description = "This is auto-generated by 'Heating-IDs'.")
	String Heating_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Thermal ESS Layer [{id}]";
}
