package io.openems.edge.oros.simulator.ess.symmetric.reacting;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Simulator ESS Symmetric OROS", //
		description = "This simulates an OROS Energy 'reacting' symmetric Energy Storage System backed by separate BMS and PCS simulators.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Maximum power increase in Percent [%]", description = "Maximum power the system is allowed to ramp up per cycle.")
	float maxPowerIncreasePercentage() default 100.F;

	@AttributeDefinition(name = "PCS-ID", description = "ID of Power Conversion System.")
	String pcs_id() default "pcs0";

	@AttributeDefinition(name = "BMS-ID", description = "ID of Battery Management System.")
	String bms_id() default "bms0";

	@AttributeDefinition(name = "Battery-Inverter target filter", description = "This is auto-generated by 'PCS-ID'.")
	String pcs_target() default "(enabled=true)";

	@AttributeDefinition(name = "Battery target filter", description = "This is auto-generated by 'BMS-ID'.")
	String bms_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Simulator ESS Symmetric OROS [{id}]";
}
