package io.openems.edge.controller.tess.surpluscharge;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Tess Surplus-Charge", //
		description = "Charges the thermal energy storage with the current PV surplus, "
				+ "up to its hardware maximum temperature.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlTessSurplusCharge0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Tess-ID", description = "ID of the ManagedThermalEss; a single storage or a Tess.Cluster.")
	String tess_id() default "tess0";

	@AttributeDefinition(name = "Thermal Efficiency", description = "Thermal output per electrical input used to convert "
			+ "the electrical surplus to a thermal target, e.g. heat pump COP (3.0), heating element (1.0).")
	double efficiency() default 1.0;

	@AttributeDefinition(name = "Tess target filter", description = "This is auto-generated by 'Tess-ID'.")
	String tess_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Tess Surplus-Charge [{id}]";
}
