package io.openems.edge.simulator.heat.tank;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.heat.tess.core.Connection;

@ObjectClassDefinition(//
		name = "Simulator Storage Tank", //
		description = "Simulates the water of a stratified storage tank, or of one layer of it, as the physical plant "
				+ "behind a Thermal ESS. The Heating devices of the Thermal ESS charge the tank, consumers draw heat "
				+ "from its top. Virtual sensors report the temperatures at the heights of the immersion sleeve and "
				+ "the connections.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "tank0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Thermal ESS-ID", description = "ID of the Thermal ESS this tank is the physical plant of. Its Heating devices charge the tank.")
	String thermalEssId() default "tess0";

	@AttributeDefinition(name = "Volume [L]", description = "Water volume in liters.")
	int volume() default 300;

	@AttributeDefinition(name = "Nodes", description = "Number of simulated horizontal nodes; more nodes resolve the stratification finer.")
	int nodes() default 10;

	@AttributeDefinition(name = "Initial Temperature [°C]", description = "Uniform water temperature at start in °C.")
	float initialTemperature() default 40;

	@AttributeDefinition(name = "Sensor Height [%]", description = "Height of the immersion sleeve relative to the tank; 0% is the bottom, 100% the top.")
	float sensorHeight() default 50;

	@AttributeDefinition(name = "Connection", description = "How the heat pump is connected: its water flows directly through the tank, or through a heat exchanger coil.")
	Connection connection() default Connection.DIRECT;

	@AttributeDefinition(name = "Supply Height [%]", description = "Height of the supply connection relative to the tank; 0% is the bottom, 100% the top.")
	float supplyHeight() default 90;

	@AttributeDefinition(name = "Return Height [%]", description = "Height of the return connection relative to the tank; 0% is the bottom, 100% the top.")
	float returnHeight() default 10;

	@AttributeDefinition(name = "Consumer Return Temperature [°C]", description = "Temperature of the water entering the bottom while consumers draw heat from the top in °C, e.g. the return of the heating circuit or the cold water inflow of domestic hot water.")
	float consumerReturnTemperature() default 30;

	@AttributeDefinition(name = "Datasource-ID", description = "ID of Simulator Datasource providing the thermal consumption [W] in the Channel '<Component-ID>/ThermalPower'.")
	String datasource_id() default "datasource0";

	@AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
	String datasource_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Simulator Storage Tank [{id}]";
}
